const validationMessage = {
    reqUsername:"Username is required!",
    reqPassword:"Password is required!",
    reqEmail:"Email is required!",
    reqCustomer:"Please select customer!",
    reqUniqueRefNumber:"Please unique reference number!",
    reqFromStoreId:"Please select from store!",
    reqToStoreId:"Please select to store!",
    reqAddress2:"Please enter address 2!",
    reqAddress1:"Please enter address 1!",
    reqCity:"Please select city!",
    reqPhone:"Please enter phone number!",
    reqName:"Please enter name!",
    reqItemName:"Please enter item name!",
    reqNumberOfPieces:"Please enter number of peices!",
    reqDimensions:"Please enter dimention!",
    reqWeight:"Enter enter weight!",
    reqMasterData:"Please enter master data!",
    reqMasterDataType:"Please enter master data type!",
    reqContactNo:"Please enter contact number!",
    reqDeliveryAttempt:"Please enter max delivery attempt!",
    reqPreferredPickupTime:"Please enter preferred pickup time",
    invalidBothCity:"Both cities can't be same!",
    invalidBothStore:"Both stores can't be same!",
    reqCountry:"Please select country!",
    reqStation:"Please select station!",
    reqProvince:"Please select province!",
    reqStation:"Please select station!",
    reqParentStation:"Please select parent station!",
}

export {validationMessage};