const validationMessage = {
    reqUsername:"Username is required!",
    reqPassword:"Password is required!",
    reqGender:"Gender is required!",
    reqEmail:"Email is required!",
    reqOldPassword:"Old password is required!",
    reqNewPassword:"New password is required!",
    ConfirmPasswordDoesnotMatch:"Confirm password doesn't match!",
    reqIdNumber:"ID number is required!",
    reqCustomer:"Please select customer!",
    reqUniqueRefNumber:"Please unique reference number!",
    reqFromStoreId:"Please select from store!",
    reqToStoreId:"Please select to store!",
    reqAddress2:"Please enter address 2!",
    reqAddress1:"Please enter address 1!",
    reqCity:"Please select city!",
    reqPhone:"Please enter phone number!",
    reqName:"Please enter name!",
    reqItemName:"Please enter item name!",
    reqNumberOfPieces:"Please enter number of peices!",
    reqDimensions:"Please enter dimention!",
    reqWeight:"Enter enter weight!",
    reqMasterData:"Please enter master data!",
    reqMasterDataType:"Please enter master data type!",
    reqContactNo:"Please enter contact number!",
    reqRole:"Please select role!",
    reqDeliveryAttempt:"Please enter max delivery attempt!",
    reqPreferredPickupTime:"Please enter preferred pickup time",
    invalidBothCity:"Both cities can't be same!",
    invalidBothStore:"Both stores can't be same!",
    reqCountry:"Please select country!",
    reqStation:"Please select station!",
    reqProvince:"Please select province!",
    reqParentStation:"Please select parent station!",
    reqFromStation:"Please select from station!",
    reqToStation:"Please select to station!",
    InvalidFromToStation:"From and to station can't be same!",
    InvalidStation:"Station is already added in list!",
    shipmentAlreadyAdded:"Shipment already added!",
    reqContainerRoute:"Please select container route!",
    reqContainerType:"Please select container type!",
    reqShipments:"Please add Shipments in container!",
}

export {validationMessage};